apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./manager.yaml
- ./auth-proxy-service.yaml
images:
- name: chirpstack-operator
  newName: ghcr.io/deepshore/chirpstack-operator
  newTag: v0.3.1
