- name: Check if the secret exists
  k8s_info:
    api_version: v1
    kind: Secret
    name: chirpstack-operator-hash-secret
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: hash_secret
  failed_when: false

- name: Create the secret if it does not exist
  when: hash_secret.resources | length == 0
  block:
    - name: Generate a random hash key
      set_fact:
        hash_key: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

    - name: Create the Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: chirpstack-operator-hash-secret
            namespace: "{{ ansible_operator_meta.namespace }}"
          type: Opaque
          data:
            hash-key: "{{ hash_key | b64encode }}"
