- block:
  - debug:
      msg: "Secret is set"

  - name: "Get {{ item.key }} from {{ item.secret }}"
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Secret
      name: "{{ item.secret }}"
      namespace: "{{ ansible_operator_meta.namespace }}"
    register: tmp_secret

  - name: "Set {{ item.var }} to value from Secret"
    set_fact:
      "{{ item.var }}": "{{ tmp_secret.resources[0].data[item.key] }}"
      
  when: item.secret

- block:
  - debug:
      msg: "Secret is not set"

  - name: "Set {{ item.var }} to empty string"
    set_fact:
      "{{ item.var }}": ""

  when: not item.secret
