---
# tasks file for Chirpstack
- debug:
    msg: "Hello from the Chirpstack Operator: '{{ ansible_operator_meta }}'"

# - name: Manage PostgreSQL
#   include_tasks: manage_postgresql.yml

# - debug:
#     msg: Check connection to Redis.

- name: Create hash secret
  include_tasks: create_hash_secret.yml

- name: Check for necessary reconciliation
  include_tasks: reconcile/main.yml
