---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - applications.deepshore.de
  resources:
  - chirpstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - applications.deepshore.de
  resources:
  - chirpstacks/finalizers
  verbs:
  - update
- apiGroups:
  - applications.deepshore.de
  resources:
  - chirpstacks/status
  verbs:
  - get
  - patch
  - update
