# permissions for end users to view chirpstacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chirpstack-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: chirpstack-operator
    app.kubernetes.io/part-of: chirpstack-operator
    app.kubernetes.io/managed-by: kustomize
  name: chirpstack-viewer-role
rules:
- apiGroups:
  - applications.deepshore.de
  resources:
  - chirpstacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - applications.deepshore.de
  resources:
  - chirpstacks/status
  verbs:
  - get
