apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - auth_proxy_client_clusterrole.yaml
  - auth_proxy_role_binding.yaml
  - auth_proxy_role.yaml
