---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - serviceaccounts
      - pods
      - pods/exec
      - pods/log
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for applications.deepshore.de/v1alpha1, Kind: Chirpstack
  ##
  - apiGroups:
      - applications.deepshore.de
    resources:
      - chirpstacks
      - chirpstacks/status
      - chirpstacks/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for applications.deepshore.de/v1alpha1, Kind: ChirpstackRegion
  ##
  - apiGroups:
      - applications.deepshore.de
    resources:
      - chirpstackregions
      - chirpstackregions/status
      - chirpstackregions/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
