apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: chirpstack-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Operator for Chirpstack
  displayName: chirpstack-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - iot
  - chirpstack
  - lorawan
  - operations
  links:
  - name: Chirpstack Operator
    url: https://chirpstack-operator.domain
  maintainers:
  - email: malte.groth@deepshore.de
    name: Malte Groth
  - email: mail@olekliemann.de
    name: Ole Kliemann
  maturity: alpha
  provider:
    name: Deepshore GmbH
    url: https://deepshore.de/
  version: 0.0.0
