- name: Define items for handling certificates from Secrets (Chirpstack)
  set_fact:
    certs_from_secrets_chirpstack:
      - volume: gateway-ca-cert
        path: gateway-ca.crt
        secret: "{{ server.configuration.chirpstack.gateway.ca_cert.secret }}"
        key: "{{ server.configuration.chirpstack.gateway.ca_cert.key }}"
      - volume: gateway-ca-key
        path: gateway-ca.key
        secret: "{{ server.configuration.chirpstack.gateway.ca_key.secret }}"
        key: "{{ server.configuration.chirpstack.gateway.ca_key.key }}"
      - volume: integration-mqtt-ca-cert
        path: integration-mqtt-ca.crt
        secret: "{{ server.configuration.chirpstack.integration.mqtt.ca_cert.secret }}"
        key: "{{ server.configuration.chirpstack.integration.mqtt.ca_cert.key }}"
      - volume: integration-mqtt-tls-cert
        path: integration-mqtt-tls.crt
        secret: "{{ server.configuration.chirpstack.integration.mqtt.tls_cert.secret }}"
        key: "{{ server.configuration.chirpstack.integration.mqtt.tls_cert.key }}"
      - volume: integration-mqtt-tls-key
        path: integration-mqtt-tls.key
        secret: "{{ server.configuration.chirpstack.integration.mqtt.tls_key.secret }}"
        key: "{{ server.configuration.chirpstack.integration.mqtt.tls_key.key }}"
      - volume: integration-mqtt-client-ca-key
        path: integration-mqtt-client-ca.key
        secret: "{{ server.configuration.chirpstack.integration.mqtt.client.ca_key.secret }}"
        key: "{{ server.configuration.chirpstack.integration.mqtt.client.ca_key.key }}"
      - volume: integration-mqtt-client-ca-cert
        path: integration-mqtt-client-ca.crt
        secret: "{{ server.configuration.chirpstack.integration.mqtt.client.ca_cert.secret }}"
        key: "{{ server.configuration.chirpstack.integration.mqtt.client.ca_cert.key }}"
      - volume: backend-interfaces-ca-cert
        path: backend-interfaces-ca.crt
        secret: "{{ server.configuration.chirpstack.backend_interfaces.ca_cert.secret }}"
        key: "{{ server.configuration.chirpstack.backend_interfaces.ca_cert.key }}"
      - volume: backend-interfaces-tls-cert
        path: backend-interfaces-tls.crt
        secret: "{{ server.configuration.chirpstack.backend_interfaces.tls_cert.secret }}"
        key: "{{ server.configuration.chirpstack.backend_interfaces.tls_cert.key }}"
      - volume: backend-interfaces-tls-key
        path: backend-interfaces-tls.key
        secret: "{{ server.configuration.chirpstack.backend_interfaces.tls_key.secret }}"
        key: "{{ server.configuration.chirpstack.backend_interfaces.tls_key.key }}"
  notify:
    - "restart server pods" 

- name: Define items for handling certificates from Secrets (Regions)
  set_fact:
    certs_from_secrets_regions:
      - volume: regions-eu433-gateway-backend-mqtt-ca-crt
        path: regions-eu433-gateway-backend-mqtt-ca.crt
        secret: "{{ server.configuration.regions.eu433.gateway.backend.mqtt.ca_cert.secret }}"
        key: "{{ server.configuration.regions.eu433.gateway.backend.mqtt.ca_cert.key }}"
      - volume: regions-eu433-gateway-backend-mqtt-tls-crt
        path: regions-eu433-gateway-backend-mqtt-tls.crt
        secret: "{{ server.configuration.regions.eu433.gateway.backend.mqtt.tls_cert.secret }}"
        key: "{{ server.configuration.regions.eu433.gateway.backend.mqtt.tls_cert.key }}"
      - volume: regions-eu433-gateway-backend-mqtt-tls-key
        path: regions-eu433-gateway-backend-mqtt-tls.key
        secret: "{{ server.configuration.regions.eu433.gateway.backend.mqtt.tls_key.secret }}"
        key: "{{ server.configuration.regions.eu433.gateway.backend.mqtt.tls_key.key }}"
      - volume: regions-eu868-gateway-backend-mqtt-ca-crt
        path: regions-eu868-gateway-backend-mqtt-ca.crt
        secret: "{{ server.configuration.regions.eu868.gateway.backend.mqtt.ca_cert.secret }}"
        key: "{{ server.configuration.regions.eu868.gateway.backend.mqtt.ca_cert.key }}"
      - volume: regions-eu868-gateway-backend-mqtt-tls-crt
        path: regions-eu868-gateway-backend-mqtt-tls.crt
        secret: "{{ server.configuration.regions.eu868.gateway.backend.mqtt.tls_cert.secret }}"
        key: "{{ server.configuration.regions.eu868.gateway.backend.mqtt.tls_cert.key }}"
      - volume: regions-eu868-gateway-backend-mqtt-tls-key
        path: regions-eu868-gateway-backend-mqtt-tls.key
        secret: "{{ server.configuration.regions.eu868.gateway.backend.mqtt.tls_key.secret }}"
        key: "{{ server.configuration.regions.eu868.gateway.backend.mqtt.tls_key.key }}"
  notify:
    - "restart server pods" 
