- operator_sdk.util.k8s_status:
    api_version: applications.deepshore.de/v1alpha1
    kind: Chirpstack
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      secrets: 
        status: "Processing"
        message: "Processing started"

- name: Manage ENVs from Secrets 
  include_tasks: envs.yml

- name: Manage Certs from Secrets 
  include_tasks: certs.yml 

- operator_sdk.util.k8s_status:
    api_version: applications.deepshore.de/v1alpha1
    kind: Chirpstack
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      secrets: 
        status: "Done"
        message: "Processing secrets completed"
