apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chirpstack-controller
  template:
    metadata:
      labels:
        app: chirpstack-controller
    spec:
      serviceAccountName: chirpstack-controller
      containers:
      - name: chirpstack-controller
        image: chirpstack-controller:latest
        imagePullPolicy: IfNotPresent
