apiVersion: v1
kind: Secret
metadata:
  name: chirpstack-env-secrets
data:
  CHIRPSTACK_POSTGRESQL_DSN_USERNAME: Y2hpcnBzdGFjaw==
  CHIRPSTACK_POSTGRESQL_DSN_PASSWORD: Y2hpcnBzdGFjaw==
  CHIRPSTACK_API_SECRET: NkVuRHdvNnZ2WHU2ZzJlbmNFaVdWMVFPMFBxa2VsUVh1UUJXTllGM2lwRQ==
