- name: Get current Secret data
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ secret_name }}"
    namespace: "{{ namespace }}"
  register: current_secret

- debug:
    msg: "Found env-secret: '{{ secret_name }}: {{ current_secret }}'"

- name: Extract current Secret data
  set_fact:
    current_secret_data: >-
      {{
        current_secret.resources[0].data | default({}) | to_json | password_hash(salt="123")
      }}

- debug:
    msg: "current_secret_data: '{{ current_secret_data }}'"

- name: Get last known Secret data from CR status
  set_fact:
    last_secret_data: "{{ current_status.secrets[secret_name] | default({}) }}"

- debug:
    msg: "last_secret_data: '{{ last_secret_data }}'"

- name: Check for changes
  set_fact:
    secret_changed: "{{ current_secret_data != last_secret_data }}"

- name: Set is_reconciled to False
  when: secret_changed
  set_fact:
    is_reconciled: False

- name: Debug EnvSecret change
  when: secret_changed
  debug:
    msg: "Secret '{{ secret_name }}' has changed."

- name: Update the accumulated Secrets status
  set_fact:
    updated_secrets_status: >-
      {{
        updated_secrets_status | combine({ secret_name: current_secret_data })
      }}

- debug:
    msg: "updated_secrets_status: '{{ updated_secrets_status }}'"
