
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: kube-rbac-proxy
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
          args:
          - "--secure-listen-address=0.0.0.0:8383"
          - "--upstream=http://127.0.0.1:8383/"
          - "--logtostderr=true"
          - "--v=0"
          ports:
          - containerPort: 8383
            protocol: TCP
            name: https
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
