name: Build and publish container images on tag

on:
  push:
    tags:
      - 'v*' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY_URL: quay.io
  ORG: maltegroth
  REPO: chirpstack-operator
  REPO_BUNDLE_IMAGE: chirpstack-operator-bundle
  OPERATOR_SDK_DL_URL: https://github.com/operator-framework/operator-sdk/releases/download/v1.32.0
  OPERATOR_SDK_CHECKSUM: "39f3d31529c49906bec8e1e3c017f536ad13faa994f02288782d9742452d4a65"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Download and install Operator SDK
        run: |
          set -ue
          set -o pipefail
          curl -sLf --retry 3 \
            -o /tmp/operator-sdk_linux_amd64 \
            https://github.com/operator-framework/operator-sdk/releases/download/v1.32.0/operator-sdk_linux_amd64
          calculated=$(sha256sum /tmp/operator-sdk_linux_amd64 | awk '{print $1}')
          if test "${calculated}" != "${OPERATOR_SDK_CHECKSUM}"; then
            echo "FAILED TO VALIDATE CHECKSUM" >&2
            echo "Download is: ${calculated}"
            echo "Should: ${OPERATOR_SDK_CHECKSUM}"
            exit 1
          fi
          sudo install -m 0755 /tmp/operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push operator image
        run: make docker-build docker-push
        env:
          IMG: ${{ env.REGISTRY_URL }}/${{ env.ORG }}/${{ env.REPO_IMAGE }}:${{ github.ref_name }}
  
      - name: Build and push bundle image
        run: make bundle bundle-build bundle-push
        env:
          IMG: ${{ env.REGISTRY_URL }}/${{ env.ORG }}/${{ env.REPO_IMAGE }}:${{ github.ref_name }}
          BUNDLE_IMG: ${{ env.REGISTRY_URL }}/${{ env.ORG }}/${{ env.REPO_BUNDLE_IMAGE }}:${{ github.ref_name }}
  