name: Catalogue

env:
  MINIKUBE_CPUS: 4
  MINKUBE_MEM: 4g

on:
  workflow_run:
    workflows: [Verify]
    types: [completed]
    branches: [main]

jobs:
  catalogue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: proudust/gh-describe@v2

# TODO
