name: Images

env:
  MINIKUBE_CPUS: 4
  MINKUBE_MEM: 4g

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main, staging/**]

jobs:
  images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - uses: drmendes/setup-k8s-operator-sdk@v1.1.5
        with:
          version: "^1.37.0"

      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.1'
        id: install

      - name: Build images
        run: make image bundle-image

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: make push-images
