name: Build and publish catalog images

on:
  push:
    branches:
      - 'main'
    paths:
      - catalog-template.yaml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY_URL: quay.io
  ORG: maltegroth
  REPO_IMAGE: chirpstack-operator-catalog
  CATALOG_DIR: catalog

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download and install opm
        run: |
          set -ue
          curl -sLf --retry 3 \
            -o /tmp/linux-amd64-opm \
            https://github.com/operator-framework/operator-registry/releases/download/v1.31.0/linux-amd64-opm
          sudo install -m 0755 /tmp/linux-amd64-opm /usr/local/bin/opm

      - name: Generate catalog file
        run: mkdir $CATALOG_DIR && make catalog-file
  
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
  
      - name: Build and push operator image
        run: make catalog-build catalog-push
        env:
          CATALOG_IMG: ${{ env.REGISTRY_URL }}/${{ env.ORG }}/${{ env.REPO_IMAGE }}:latest